### ISSUE TITLE
Feedback - Week 18 Assignment

### ISSUE THREAD

**Issue by ntuvera** [matt-taggart/news_scraper_hw_18#1]
Hey @matt-taggart, I cloned your repo and took a look at the news scraper app and... OMG PUPPIES. lulz

It looks like you've got the scrape functionality working with cheerio, but we're also missing the ability to add/delete notes.  I still ran into some issues with your scraped data.  It appears your validation of uniqueness is causing issues when I load the `/` route.  You're scraping and storing whenever I hit the home route, but the new data doesn't save because it's not allowed to due to uniqueness.  

Given the uniqueness validation, you may want to clear the collection before you try to save documents to avoid this server crashing bug.  

On the plus side, you've got the MVC file/folder structure, I've been wanting to see for a while.  You're exporting/requiring is at a higher level than others and it makes sense.  This is a pattern/habit you'll want to hold onto.

So you did a pretty good job with what you've accomplished minus the server crashing bug and missing note functionality.  You get extra points for puppies.  Take a look at www.placecage.com if you want some other place holder images.  It's hilarious.  Fix up the missing functionality when you get time, you got the gist of scraping, but your mongo transaction needs a little work.

**Comment by matt-taggart** [comment]
@ntuvera:  Hahaha glad you enjoyed the puppies!   I recall having a difficult time scraping the image src for Vice for some reason, so I left the dogs as a placeholder.  Thank you for the feedback - I'll definitely look into adding logic to clear the collection before saving - if I run into trouble I'll let you know.
